# -*- coding: utf-8 -*-
"""TPU-Transfer-learning.ipynb

Automatically generated by Colaboratory.

"""

!uname -a && python -V && pip -V

!apt-get update;apt-get upgrade -y

!apt-get install -y protobuf-compiler python-pil python-lxml python-tk \
autoconf automake libtool curl make g++ unzip wget git nano \
libgflags-dev libgoogle-glog-dev liblmdb-dev libleveldb-dev \
libhdf5* python3-dev python3-numpy python3-skimage gfortran libturbojpeg \
python-dev python-numpy python-skimage python3-pip python-pip \
libboost-all-dev libopenblas-dev libsnappy-dev software-properties-common \
protobuf-compiler python-pil python-lxml python-tk libfreetype6-dev pkg-config libpng12*

!pip install pip==18.0.0 --upgrade

!pip install --user Cython opencv-python lxml

!git clone https://github.com/tensorflow/models.git

from google.colab import files
files.upload()

!ls -l

!mv collabo.zip models/research

%cd models/research
!unzip collabo.zip

!rm collabo.zip

!chmod +x constants.sh
!chmod +x prepare_checkpoint_and_dataset.sh
!chmod +x retrain_detection_model.sh
!chmod +x protoc_update.sh
!chmod +x convert_checkpoint_to_edgetpu_tflite.sh
!cp object_detection_evaluation.py object_detection/utils
!mkdir configs

!git clone https://github.com/pdollar/coco.git
%cd coco/PythonAPI
!python3 setup.py install

%cd ../..

!wget https://github.com/protocolbuffers/protobuf/archive/v3.7.0.zip
!unzip v3.7.0.zip;rm v3.7.0.zip
%cd protobuf-3.7.0
!./autogen.sh
!./configure
!make -j$(($(nproc) + 1))

!make install

%cd python
!export LD_LIBRARY_PATH=../src/.libs
!python3 setup.py build --cpp_implementation
!python3 setup.py test --cpp_implementation
!python3 setup.py install --cpp_implementation
!ldconfig

%cd ../..

!protoc --version

!./prepare_checkpoint_and_dataset.sh --network_type mobilenet_v2_ssd --train_whole_model false

!source "$PWD/constants.sh"
%env NUM_TRAINING_STEPS=1000
%env NUM_EVAL_STEPS=100
!rm -rf learn/train
!./retrain_detection_model.sh \
  --num_training_steps ${NUM_TRAINING_STEPS} \
  --num_eval_steps ${NUM_EVAL_STEPS}

!ls -l learn/train

!./convert_checkpoint_to_edgetpu_tflite.sh --network_type mobilenet_v2_ssd --checkpoint_num 292

!ls -l learn/models

from google.colab import files
files.download("learn/models/output_tflite_graph.tflite")
